Diagnostics: Fixes some issues and improves scripts
(cherry picked from commit ace24d82fcbf47d9437f21a1a96fa821e87a473f)

diff --git a/scripts/nslookup_launch b/scripts/nslookup_launch
--- a/scripts/nslookup_launch
+++ b/scripts/nslookup_launch
@@ -18,54 +18,49 @@ nslookup_launch() {
 	[ -e "${LOG_FILE}" ] && rm ${LOG_FILE}
 	while [ $i -lt "$cnt" ]; do
 		i=$((i+1))
-		time1=$(date +%s)
-		if [ -z "$dnsserver" ]; then
-			nslookup "$hostname" >>${LOG_FILE} 2>&1
-		else
-			nslookup "$hostname" "$dnsserver" >>${LOG_FILE} 2>&1
-		fi
-		time2=$(date +%s)                       
-		timeresponse=$(($(($time2-$time1))*1000))
-		echo "ResponseTime: $timeresponse" >>${LOG_FILE}
+		nslookup -debug $hostname $dnsserver >>${LOG_FILE} 2>&1
+		error_code="$?"
+		nxd=$(cat ${LOG_FILE} | grep "NXDOMAIN")
+		[ -n "$nxd" ] && { $UCI_SET_BBF_DMMAP dmmap_diagnostics.nslookup.DiagnosticState=Error_DNSServerNotResolved; $UCI_COMMIT_BBF_DMMAP; return; }
+		[ "$error_code" != "0" ] && { $UCI_SET_BBF_DMMAP dmmap_diagnostics.nslookup.DiagnosticState=Error_Other; $UCI_COMMIT_BBF_DMMAP; return; }
 		echo "++++++++++++++++++++++++++++++" >>${LOG_FILE}
 	done
 
 	while IFS= read line; do
-	[ -z "$line" ] && continue;
-	server=$(echo "$line" | tr -d '\t' | tr -d ' ' | grep "Server:" | awk -F':' '{print $2}')
+		[ -z "$line" ] && continue;
+		server=$(echo "$line" | tr -d '\t' | tr -d ' ' | grep "Server:" | awk -F':' '{print $2}')
+	
+		if [ -n "$server" ] && [ "$server" = "0.0.0.0" ]; then
+		        status="Error_DNSServerNotAvailable"
+		        continue
+		elif [ -n "$server" ]; then
+		        dns_server_ip=$server
+		        continue
+		fi
 
-	if [ -n "$server" ] && [ "$server" = "0.0.0.0" ]; then
-	        status="Error_DNSServerNotAvailable"
-	        continue
-	elif [ -n "$server" ]; then
-	        dns_server_ip=$server
-	        continue
-	fi
+		var=$(echo "$line" | tr -d '\t' | tr -d ' ' | grep "Name:" | awk -F':' '{print $2}')
+		[ -n "$var" ] && { HostNameReturned=$var; status="Success"; AnswerType="Authoritative"; success_count=$((success_count+1)); continue; }
+	
+		var=$(echo "$line" | grep "Address: " | awk -F':' '{print substr($0, index($0,$2))}' | tr -d '\t' | tr -d ' ')
+		[ -n "$var" ] && { [ -z "$address" ] && address="$var" || address="$address,$var"; continue; }
+	
+		var=$(echo "$line" | grep "completed" | awk -F'in' '{print $2}' | tr -d 'ms:\t ')
+		[ -n "$var" ] && { ResponseTime=$var; continue; }
 
-	var=$(echo "$line" | tr -d '\t' | tr -d ' ' | grep "Name:" | awk -F':' '{print $2}')
-	[ -n "$var" ] && { HostNameReturned=$var; status="Success"; AnswerType="Authoritative"; success_count=$((success_count+1)); continue; }
-
-	var=$(echo "$line" | grep "Address: " | awk -F':' '{print substr($0, index($0,$2))}' | tr -d '\t' | tr -d ' ')
-	[ -n "$var" ] && { [ -z "$address" ] && address="$var" || address="$address,$var"; continue; }
-
-	var=$(echo "$line" | tr -d '\t' | tr -d ' ' | grep "ResponseTime:" | awk -F':' '{print $2}')
-	[ -n "$var" ] && { ResponseTime=$var; continue; }
-
-	echo "$line" | grep 'Can' >/dev/null 2>&1 && {  continue; }
-	echo "$line" | grep 'connection timed out' >/dev/null 2>&1 && { AnswerType="None"; status="Error_Timeout"; continue; }
-	echo "$line" | grep 'Non-authoritative' >/dev/null 2>&1 && { AnswerType="NonAuthoritative"; continue; }
-
-	if echo "$line" | grep '++++++++++++++++++++++' >/dev/null 2>&1; then
-		$UCI_ADD_BBF_DMMAP dmmap_diagnostics NSLookupResult
-		$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].Status="$status"
-		$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].AnswerType="$AnswerType"
-		$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].HostNameReturned="$HostNameReturned"
-		$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].IPAddresses="$address"
-		$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].DNSServerIP="$dns_server_ip"
-		$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].ResponseTime="$ResponseTime"
-		j=$((j+1))
-		address=""
-	fi
+		echo "$line" | grep 'connection timed out' >/dev/null 2>&1 && { AnswerType="None"; status="Error_Timeout"; continue; }
+		echo "$line" | grep 'Non-authoritative' >/dev/null 2>&1 && { AnswerType="NonAuthoritative"; continue; }
+	
+		if echo "$line" | grep '++++++++++++++++++++++' >/dev/null 2>&1; then
+			$UCI_ADD_BBF_DMMAP dmmap_diagnostics NSLookupResult
+			$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].Status="$status"
+			$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].AnswerType="$AnswerType"
+			$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].HostNameReturned="$HostNameReturned"
+			$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].IPAddresses="$address"
+			$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].DNSServerIP="$dns_server_ip"
+			$UCI_SET_BBF_DMMAP dmmap_diagnostics.@NSLookupResult[$j].ResponseTime="$ResponseTime"
+			j=$((j+1))
+			address=""
+		fi
 	done <${LOG_FILE}
 	rm -f ${LOG_FILE}
 	$UCI_SET_BBF_DMMAP dmmap_diagnostics.nslookup.SuccessCount=$success_count
